# Generated by Django 4.0.2 on 2024-05-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
